name: IOS Build APP to Appspack

on:
  workflow_call:
    inputs:
        branch:
          description: 'git branch'
          type: string
          required: true
        environment:
          description: 'environment'
          type: string
          required: true
        platform:
          description: 'platform'
          type: string
          required: true
        scheme:
          type: string
          required: true
    secrets:
        git-path: 
          description: 'Git Path'
          required: true
        ios-p12:
          description: 'P12  base64'
          required: true
        ios-p12-pwd:
          description: 'P12 Pwd'
          required: true
        ios-provision:
          description: 'Provision base64'
          required: true
        ios-provision-pwd:
          description: 'ios-provision password'
        app-id:
          required: true
        api-key:
          required: true
        install-pwd:
          required: true
    
jobs:
  build:
    runs-on: macos-12
    steps:

    - name: Get current time
      uses: josStorer/get-current-time@v2
      id: current-time
      with:
        format: "YYYY-MM-DD_HH-mm"
        utcOffset: "+08:00"

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4'
        
    - name: Clone Project From Gitlab
      run: | 
        git config --global user.email "cicd_admin@mtelnet.com"
        git config --global user.name "cicd_admin"
        git clone --single-branch --branch ${{ inputs.branch }} ${{ secrets.git-path }} .
    
    # Remember to set each Environment Gymfile on project git
    - name: Move Environment Gymfile
      run: |
          cp ./fastlane/Gymfile.${{ inputs.environment }} ./fastlane/Gymfile
          cat ./fastlane/Gymfile
    
    - uses: actions/cache@v1
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
        
    - name: Install the Apple certificate and provisioning profile & Build
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.ios-p12 }}
        P12_PASSWORD: ${{ secrets.ios-p12-pwd }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.ios-provision }}
        KEYCHAIN_PASSWORD: ${{ secrets.ios-provision-pwd }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
        
        pod deintegrate
        pod install
        OUTPUT_NAME="${{ inputs.scheme }}_IOS_1.0.0_${{ steps.current-time.outputs.formattedTime }}_${GITHUB_SHA}"
        echo $OUTPUT_NAME
        ls -lur ./fastlane
        fastlane gym --export_method ad-hoc --output_name $OUTPUT_NAME --include_bitcode false --include_symbols false
        ls -ltr ./build
    
    - name: Upload to Appspack   
      run: | 
        DIR=$(pwd)
        IPAPATH=$DIR"/build/"$(ls ./build | grep 'ipa')
        echo $IPAPATH
        VERSION=$(ls ./build | grep 'ipa' | sed 's/\(.*\).ipa/\1/g')
        echo 'Version:' + $VERSION
        echo 'IPA PATH:' $IPAPATH
        echo 'Upload IPA to Appspack...'
        fastlane upload_appspack \
        env:${{ inputs.environment }} \
        version:$VERSION \
        filepath:$IPAPATH \
        app_id:${{ secrets.app-id }} \
        api_key:${{ secrets.api-key }} \
        title:$VERSION \
        description:$VERSION  \
        tags:${{ inputs.environment }},${{ inputs.platform }} \
        install_remarks:$VERSION  \
        install_pwd:${{ secrets.install-pwd }}
