name: IOS Dev

on: push
  
jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            path: main
        - name: Call Fastlane
          run: |
            ls -ltr
            cd common-devops-action
            fastlane call_url
            echo $ENV_TEST
