name: IOS Dev

on: push
  
jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            path: main
        - name: Call Fastlane
          run: |
            ls -ltr
            pwd
            cd main
            fastlane call_url
            echo "==separator=="
            cat response.json
